CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT);
CREATE TABLE IF NOT EXISTS "attrs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "label" TEXT, "type" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "categories" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "title" TEXT, "parent_id" INTEGER CONSTRAINT "categories_parent_id_fkey" REFERENCES "categories"("id"), "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "categories_attrs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "category_id" INTEGER CONSTRAINT "categories_attrs_category_id_fkey" REFERENCES "categories"("id"), "attr_id" INTEGER CONSTRAINT "categories_attrs_attr_id_fkey" REFERENCES "attrs"("id"), "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "products" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "title" TEXT, "description" TEXT, "price" DECIMAL, "category_id" INTEGER CONSTRAINT "products_category_id_fkey" REFERENCES "categories"("id"), "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL, "highlight_id" INTEGER CONSTRAINT "products_highlight_id_fkey" REFERENCES "highlights"("id") ON DELETE SET NULL, "location_id" INTEGER CONSTRAINT "products_location_id_fkey" REFERENCES "locations"("id") ON DELETE SET NULL, "lat" DECIMAL, "lng" DECIMAL);
CREATE TABLE IF NOT EXISTS "products_attrs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "product_id" INTEGER CONSTRAINT "products_attrs_product_id_fkey" REFERENCES "products"("id"), "attr_id" INTEGER CONSTRAINT "products_attrs_attr_id_fkey" REFERENCES "attrs"("id"), "value" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "email" TEXT NOT NULL COLLATE NOCASE, "hashed_password" TEXT NOT NULL, "confirmed_at" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE UNIQUE INDEX "users_email_index" ON "users" ("email");
CREATE TABLE IF NOT EXISTS "users_tokens" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "user_id" INTEGER NOT NULL CONSTRAINT "users_tokens_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "token" BLOB NOT NULL, "context" TEXT NOT NULL, "sent_to" TEXT, "inserted_at" TEXT NOT NULL);
CREATE INDEX "users_tokens_user_id_index" ON "users_tokens" ("user_id");
CREATE UNIQUE INDEX "users_tokens_context_token_index" ON "users_tokens" ("context", "token");
CREATE TABLE IF NOT EXISTS "highlights" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "points" INTEGER, "max_points" INTEGER, "point_price" INTEGER, "duration_days" INTEGER, "expired_at" TEXT, "user_id" INTEGER CONSTRAINT "highlights_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "highlights_user_id_index" ON "highlights" ("user_id");
CREATE UNIQUE INDEX "products_highlight_id_index" ON "products" ("highlight_id");
CREATE TABLE IF NOT EXISTS "locations" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT, "loc_type" TEXT, "lat" DECIMAL, "lng" DECIMAL, "parent_id" INTEGER CONSTRAINT "locations_parent_id_fkey" REFERENCES "locations"("id"), "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "locations_parent_id_index" ON "locations" ("parent_id");
CREATE INDEX "locations_lat_lng_index" ON "locations" ("lat", "lng");
CREATE INDEX "products_location_id_index" ON "products" ("location_id");
CREATE INDEX "products_lat_lng_index" ON "products" ("lat", "lng");
INSERT INTO schema_migrations VALUES(20230904145253,'2023-09-04T15:08:25');
INSERT INTO schema_migrations VALUES(20230905142737,'2023-09-05T14:28:07');
INSERT INTO schema_migrations VALUES(20230912001305,'2023-09-12T00:28:28');
INSERT INTO schema_migrations VALUES(20230912002843,'2023-09-12T00:40:39');
